swagger: 2.0
info:
  description: "Content-Based Music Retrieval"
  version: "1.0.0"
  title: "SMIR"
  contact:
    name: "David Garfinkle"
    email: "david.garfinkle@mail.mcgill.ca"
host: "http://132.206.14.238:8000"
paths:
  /search:
    get:
      operationId: "search"
      summary: "Request the service to perform a content-based music retrieval search"
      produces: 
        - "text/html"
        - "application/json"
      parameters:
        - name: "encoding"
          in: "query"
          description: "Indicates the music encoding language of the query string"
          type: "string"
        - name: "query"
          in: "query"
          description: "A music query string"
          type: "string"
      responses:
        200:
          description: "The server successfully completed a search for the music query and is returning the result(s)" 
          schema:
            type: "array"
            items:
              $ref: "#/components/schemas/occurrence"
  /piece:
    get:
      operationId: "get-piece"
      summary: "Request the excerpt, highlighted excerpt, or entirety of a piece in the database"
      produces: 
        - "application/xml"
        - "application/svg"
      parameters:
        - name: "piece"
          in: "path"
          description: "The unique name of the piece document"
          required: true
          type: "string"
        - name: "m"
          in: "query"
          description: "List of measure numbers for excerpt"
          type: "array"
          items:
            type: "integer"
        - name: "n"
          in: "query"
          description: "Indices of notes to highlight"
          type: "array"
          items:
            type: "integer"
        - name: "c"
          in: "query"
          description: "Colour of the highlighted notes"
          type: "string"
          default: "red"
      responses:
        200:
          description: "Returning a piece" 
          schema:
            type: "string"
definitions:
  occurrence:
    type: "object"
    properties:
      pieceName:
        type: "string"
      excerpt:
        type: "object"
        properties:
          encoding: "string"
          content: "string"
      measures:
        type: "array"
        items:
          type: "integer"
      noteIndices:
        type: "array"
        items: 
          type: "integer"
      diatonicOcc:
        type: "boolean"
      transposition:
        type: "integer"
