swagger: 2.0
info:
  description: "Content-Based Music Retrieval"
  version: "1.0.0"
  title: "SMIR"
  contact:
    name: "David Garfinkle"
    email: "david.garfinkle@mail.mcgill.ca"
host: "http://132.206.14.238:8000"
paths:
  /search:
    get:
      operationId: "search"
      summary: "Request the service to perform a content-based music retrieval search"
      produces: 
        - "text/html"
        - "application/json"
      parameters:
        - name: "encoding"
          in: "query"
          description: "Indicates the music encoding language of the query string"
          type: "string"
        - name: "query"
          in: "query"
          description: "A music query string"
          type: "string"
        - name: "minOccLength"
          in: "query"
          description: "Filter results for minimum length"
          type: "integer" 
        - name: "maxTargetWindow"
          in: "query"
          description: "Filter results for a maximum sorted distance between highlighted notes"
          type: "integer"
        - name: "transposition"
          in: "query"
          description: "An enum: what type of transpositions of the query will be returned"  
          type: "integer"
        - name: "corpus"
          in: "query"
          description: "Select a corpus to search through"
          type: "string"
      responses:
        200:
          description: "The server successfully completed a search for the music query and is returning the result(s)" 
          schema:
            type: "array"
            items:
              $ref: "#/definitions/occurrence"
  /piece:
    get:
      operationId: "get-piece"
      summary: "Request the excerpt, highlighted excerpt, or entirety of a piece in the database"
      produces: 
        - "application/xml"
        - "application/svg"
      parameters:
        - name: "piece"
          in: "path"
          description: "The unique name of the piece document"
          required: true
          type: "string"
        - name: "n"
          in: "query"
          description: "Indices of notes to highlight"
          type: "array"
          items:
            type: "integer"
        - name: "c"
          in: "query"
          description: "Colour of the highlighted notes"
          type: "string"
          default: "red"
      responses:
        200:
          description: "Returning a piece" 
          schema:
            type: "string"
definitions:
  paginatedResults:
    type: "object"
    properties:
      count:
        type: "integer"
      pages:
        type: "array"
        items:
          type: "object"
          properties:
            pageNum:
              type: "integer"
            occurrences:
              type: "array"
              items:
                $ref: "#/definitions/occurrence"
  occurrence:
    type: "object"
    properties:
      pieceName:
        type: "string"
      targetNotes:
        type: "array"
        items: 
          type: "integer"
      diatonicOcc:
        type: "boolean"
      transposition:
        type: "integer"
      rank:
        type: "integer"
