/**
 * SMIR
 * Content-Based Music Retrieval
 *
 * OpenAPI spec version: 1.0.0
 * Contact: david.garfinkle@mail.mcgill.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OccurrenceExcerpt } from './occurrenceExcerpt';


export interface Occurrence { 
    pieceName?: string;
    excerpt?: OccurrenceExcerpt;
    measures?: Array<number>;
    noteIndices?: Array<number>;
    diatonicOcc?: boolean;
    transposition?: number;
}
