/**
 * SMIR
 * Content-Based Music Retrieval
 *
 * OpenAPI spec version: 1.0.0
 * Contact: david.garfinkle@mail.mcgill.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Occurrence } from './occurrence';


export interface PaginatedResultsPages { 
    occurrences?: Array<Occurrence>;
    pageNum?: number;
}
